### ISSUE TITLE
Interfaz grafica

### ISSUE THREAD

**Issue by AriDevK** [MrKrrot/proyecto-python#1]
Pueden utilizar librerias de interfaces para terminal para que se vea diferente a la tipica aplicacion de tutorial; yo les recomiendo:
- [console menu](https://github.com/aegirhall/console-menu)
- [terminal table](https://github.com/matthewdeanmartin/terminaltables)

Todas permiten utilizar colores en la terminal y no son dificiles de utilizar.

✨Regards

<img src="https://ih1.redbubble.net/image.2520271851.1071/st,small,507x507-pad,600x600,f8f8f8.jpg" width="200" />
PD: Ya dame follow Rafa >:c

**Comment by MrKrrot** [comment]
Tenkius, justo andaba buscando algo comop las tablas pero no conozco muchas librerias de python jsjsjsjs

Pd: Ya te tengo en follow desde hace bastante wtf xddd
